{
 "title": "ksqlDB Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "OS Free Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_threads_current" }
   ]
  },
  {
   "title": "ACTIVE QUERIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_default_num_active_queries"
    }
   ]
  },
  {
   "title": "NOT RUNNING QUERIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_default_ksql_engine_query_stats_NOT_RUNNING_queries"
    }
   ]
  },
  {
   "title": "IDLE QUERIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_default_num_idle_queries"
    }
   ]
  },
  {
   "title": "RUNNING QUERIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_default_ksql_engine_query_stats_RUNNING_queries"
    }
   ]
  },
  {
   "title": "ERROR QUERIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_default_ksql_engine_query_stats_ERROR_queries"
    }
   ]
  },
  {
   "title": "Messages Produced/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_confluent_ksql_default_ksql_engine_query_stats_messages_produced_per_sec"
    }
   ]
  },
  {
   "title": "Messages consumed/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "io_confluent_ksql_metrics_confluent_ksql_default_ksql_engine_query_stats_messages_consumed_per_sec"
    }
   ]
  },
  {
   "title": "Consumer Records Lag Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg"
    }
   ]
  },
  {
   "title": "jvm_info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "jvm_info" }
   ]
  }
 ]
}